### PR TITLE
update module with latest changes

### PR DESCRIPTION
**Pull request by yadavprakash**
## what
- update module with latest change
- update module with latest terraform version 

## why
- need to update module with dynamic
- update terraform version

### CODE REVIEW

**Review by themaniskshah — APPROVED** [review]
LGTM!

**Review by nikita-cd — APPROVED** [review]
!LGTM

**Review by archit-cd — COMMENTED** [review]
LGTM

**Review by archit-cd — APPROVED** [review]

**Review by omsharma07 — APPROVED** [review]
LGTM

**Pull request merged**
